### ISSUE TITLE
Dashboard for this

### ISSUE THREAD

**Issue by rufuspollock** [datasets/covid-19#24]
Create a simple dashboard similar to e.g. https://carbon.datahub.io or https://london.datahub.io to present this information and provide an open source basis for others to create their own dashboards quickly esp per country.

## Tasks

* [x] Design the dashboard
* [x] Sketch out dashboard
* [x] Implement

### Implement

* [x] Check out existing dashboards 
  * [x] Check out carbon project https://github.com/datopian/carbondoomsday
  * [x] Check out london project

### Mockup

<img width="609" alt="Screen Shot 2020-04-09 at 16 18 29" src="https://user-images.githubusercontent.com/17809581/78885234-0d8c7c00-7a7e-11ea-97c8-a2631769e009.png">

### Charting libraries

* ~~Use the vega work we have~~
* ~~https://nivo.rocks/line~~
* Use plotly js

### v2 - added line chart with cumulative cases in top 5 countries

<img width="650" alt="Screen Shot 2020-04-14 at 22 40 46" src="https://user-images.githubusercontent.com/17809581/79250792-0a8bf400-7ea1-11ea-94dd-98b9e18d90be.png">

### v3 - ability to select a country and showing a graph with cumulative cases, deaths per day and new cases per day

![dashboard v3](https://user-images.githubusercontent.com/17809581/79249964-d82dc700-7e9f-11ea-8871-4dfd9d7da648.png)

### v4 - added figure for showing cases per 100k population

![dashboard v4](https://user-images.githubusercontent.com/17809581/79250207-293dbb00-7ea0-11ea-9cac-5ebb54b5e60c.png)

### v5 - added choropleth map (again)

![dashboard v5](https://user-images.githubusercontent.com/17809581/79301104-76ef0d80-7f0a-11ea-9fb5-815cf87cfca0.png)

---

### Charts to do

* Time series of cases
* Chloropeth of cases by country

# Needs Analysis

## Domain Model

Value: (new confirmed) cases, deaths, recovered

Dimensions:

* Time
* Country
  * SubCountry i.e. Province/State
  * City

### Key figures (for world and per country)

When wanting to know about the situation I want to see key figures such as total number of people infected/recovered/died, so that I understand current status of the situation in the World.

* In my country, in my locality

Specific items:

* How many total cases? [single figure]
* How many total cases (over time) i.e. cumulative? [time series]
* How many cases "per day" over time [time series]
* What is the mortality rate? (how that has changed over time?)
* Cases in specific locations (lon, lat and by country)
* Total Case by country (now)
* Case by country (over time)

"What's happening in my country" => Ditto but just with my country

### What's changed

* When I see the COVID-19 dashboard, I want to see a figure showing change of total number of people affected in last 24h (something like stock market price), so that I can know if it's getting better or not.

Secondary

* When I see the COVID-19 dashboard, I want to check number of cases per capita, so that I can compare my country against others.

Tertiary

* When I see the COVID-19 dashboard, I want to see viz showing some correlation with economic indicators (by country), so that I can assess the economic impact.

Meta

* When I see the COVID-19 dashboard, I want to be able to share it via twitter/facebook/instagram, so that my friends/colleagues can also check it out.
* ...

**Comment by Akuukis** [comment]
Hello! During another hackathon in Latvia our team have built a dashboard based on the same data, that also estimates real cases based on [Tomas Pueyo](https://medium.com/@tomaspueyo/coronavirus-act-today-or-people-will-die-f4d3d9cd99ca) model. It's currently in polishing phase, and should be finished & open-sourced in 1-3 days. You can check it out here: https://pandemic-estimator.net

I would be more than happy to unite forces. Let me know if you see us a good fit & what's missing.

**Comment by deleugpn** [comment]
I'm maintaining https://corona.deleu.dev using the data provided here

**Comment by rufuspollock** [comment]
@deleugpn that's great to hear! @Akuukis too. 

Do you have the source code for these anywhere?

**Comment by Akuukis** [comment]
@rufuspollock yes, I will publish it in open-source once I finish up cleanup. Here's the placeholder repo https://github.com/akuukis/pandemic-estimator

**Comment by Akuukis** [comment]
@rufuspollock It's open-sourced now
- website: https://pandemic-estimator.net
- repo: https://github.com/akuukis/pandemic-estimator

**Comment by dslakind** [comment]
Using your data I have created a mathematical model that seems to closely predict the total global deaths on a daily basis (at least for the last three days). I don't know when the number of deaths will peak or when the rate of change will slow down so the model doesn't take these factors into consideration.  The model can be found on Desmos at the following link: 
https://www.desmos.com/calculator/r0dbwemr7i

**Comment by rufuspollock** [comment]
@dslakind great do you want to edit this page and add a link to your work https://datahub.io/collections/coronavirus - you can edit it here https://github.com/datasets/awesome-data/blob/master/coronavirus.md

**Comment by Akuukis** [comment]
@rufuspollock I checked the links but don't see how I could fit that nicely in. Feel free to do a quick oneliner yourself if you wish, or let me know a bit more details please.

**Comment by anuveyatsu** [comment]
Closing this as we have moved our dashboard work to https://github.com/datopian/covid-19
